version: '3.9'

services:
  database:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=XEPDB1
      - ORACLE_PWD=pas5w0rd!
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: