version: '3.9'

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=XEPDB1
      - ORACLE_PWD=pas5w0rd!
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

networks:
  oracle-network:

volumes:
  oracle-data:
    driver: local